### ISSUE TITLE
开启PIE下断点的问题

### ISSUE THREAD

**Issue by GotALeanSip** [RoderickChan/pwncli#10]
![image](https://user-images.githubusercontent.com/74945960/197115356-55459386-fafe-4eca-b78d-32cc19cc2649.png)
使用-b b+0x202050下的断点没有加上相对偏移

**Comment by RoderickChan** [comment]
> ![image](https://user-images.githubusercontent.com/74945960/197115356-55459386-fafe-4eca-b78d-32cc19cc2649.png) 使用-b b+0x202050下的断点没有加上相对偏移

可以提供一下题目附件吗？

**Comment by GotALeanSip** [comment]
我这里不管那个elf都不能下带PIE的断点，应该是我环境的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RoderickChan/pwncli"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月21日(星期五) 下午4:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RoderickChan/pwncli] 开启PIE下断点的问题 (Issue #10)





  
 使用-b b+0x202050下的断点没有加上相对偏移
  
可以提供一下题目附件吗？

**Comment by GotALeanSip** [comment]
解决了，谢谢师傅！
