### ISSUE TITLE
用wsl卡死

### ISSUE THREAD

**Issue by Theropej** [RoderickChan/pwncli#37]
不是关于师傅项目的问题； 就是今天用wsl搭环境，然后老是莫名其妙的卡退，然后又进不去，网上说 netsh winsock reset 然后重启，可以解决但是 用了一段时间又卡，师傅看你也是用wsl 有什么解决办法吗😣😭😭

**Comment by RoderickChan** [comment]
可是提供更多的信息吗?比如报错之类的，看我之前有没有遇到过，可以帮你协助解决



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月16日(周四) 晚上7:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [RoderickChan/pwncli] 用wsl卡死 (Issue #37)




 
不是关于师傅项目的问题； 就是今天用wsl搭环境，然后老是莫名其妙的卡退，然后又进不去，网上说 netsh winsock reset 然后重启，可以解决但是 用了一段时间又卡，师傅看你也是用wsl 有什么解决办法吗😣😭😭

**Comment by Theropej** [comment]
![5(4_FDE6M$4LH3RH57PDY7S](https://github.com/RoderickChan/pwncli/assets/89021566/d1458aa6-a209-49ac-b725-a24eaf027d37)
![QQ_PIVM)P~_U7JIWAD17AE](https://github.com/RoderickChan/pwncli/assets/89021566/7aede788-7a6c-4915-9403-b6abb0b13909)
![})526GR{D5FS7NNO3K0DC1A](https://github.com/RoderickChan/pwncli/assets/89021566/251d03f1-fdaa-4fa4-82a6-1c814a4982d3)
![QQ截图20231116203314](https://github.com/RoderickChan/pwncli/assets/89021566/e82ce776-c1d5-4da9-8d0b-59106c8e90f6)
似乎除了  --help命令以外的都不行，直接卡死

**Comment by Theropej** [comment]
有时候用着用着就突然断掉，然后就和上面图一样 😭😭😭

**Comment by RoderickChan** [comment]
这个可能需要上windbg分析下，看代码卡在哪里。或者把wsl更新到最新的版本 或者重装wsl。


我之前也没有遇到过你这个问题。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月16日(周四) 晚上8:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RoderickChan/pwncli] 用wsl卡死 (Issue #37)




 
有时候用着用着就突然断掉，然后就和上面图一样 😭😭😭
