### ISSUE TITLE
pwncli -w  

### ISSUE THREAD

**Issue by Theropej** [RoderickChan/pwncli#38]
![image](https://github.com/RoderickChan/pwncli/assets/89021566/de85281d-3600-46b6-8591-d2cccefcfa8e)
版本 ubuntu22.04
python 3.10.12
wsl：
![image](https://github.com/RoderickChan/pwncli/assets/89021566/ccddc409-977e-4019-b9bc-9cf97773c16d)

这是什么原因 师傅
我又来了😭😭😭

**Comment by RoderickChan** [comment]
> ![image](https://user-images.githubusercontent.com/89021566/283490467-de85281d-3600-46b6-8591-d2cccefcfa8e.png) 版本 ubuntu22.04 python 3.10.12 wsl： ![image](https://user-images.githubusercontent.com/89021566/283490899-ccddc409-977e-4019-b9bc-9cf97773c16d.png)
> 
> 这是什么原因 师傅 我又来了😭😭😭

就是你的发行版的名字不是默认的Ubuntu-XX.XX这种格式，所以没有找到你的发行版。这个错误我标记一下，之后有时间会处理。

BTW，我建议使用tmux，比wsl好用。

**Comment by Theropej** [comment]
师傅打awd吗，pwn靶机一般怎么加固哇，上次打过一次，有点懵，网上也没教程😭😭😭😭

**Comment by RoderickChan** [comment]
> 师傅打awd吗，pwn靶机一般怎么加固哇，上次打过一次，有点懵，网上也没教程😭😭😭😭

1. 用一些工具打patch补丁，比如IDA手动打，pwnpatch脚本打（常规做法）
2. 配置防火墙，抓流量禁IP（有时候不行）
3. 设置蜜罐（有时候不行）
4. ....其他得看比赛规则了
