### ISSUE TITLE
似乎不支持IDA调试?

### ISSUE THREAD

**Issue by raddyfiy** [RoderickChan/pwncli#41]
用最原始的IDA调试方法， 用input()卡住后附加进程，走几步程序会跑飞，执行到最后但ida跟丢了。
搜issue也没有类似的问题，不会大家真的只用GDB吧，TQL

**Comment by RoderickChan** [comment]
> 

pwn的话还是建议使用gdb调试。如果非要用IDA attach到进程上调试，可以多加几个input，因为你一下输入了很多，IDA就会跑飞。
