### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by Arashimu** [RoderickChan/pwncli#7]
When I finsh installing pwncli following the guide and  input "pwncli -h"，there has an error:
pkg_resources.DistributionNotFound: The 'typing; python_version < "3.5"' distribution was not found and is required by pathlib2
and the version of the python is 3.10
how could I solve this problem

**Comment by RoderickChan** [comment]
How did you install pwncli? I install pwncli from sourcecode in python 3.10.4 on Ubuntu-22.04, and it works well
